version: '3.4'

services:
  solr660:
    image: solr:6.6.0
    volumes:
      - .:/opt/solr/server/solr
    ports:
      - 8983:8983
    working_dir: /opt/solr/server/solr
    command: sh -c "solr start -f"
    environment:
      SOLR_SSL_ENABLED: "true"
      SOLR_SSL_KEY_STORE: "solr/solr-ssl.keystore.jks"
      SOLR_SSL_KEY_STORE_PASSWORD: "secret"
      SOLR_SSL_TRUST_STORE: "solr/solr-ssl.keystore.jks"
      SOLR_SSL_TRUST_STORE_PASSWORD: "secret"
      SOLR_SSL_NEED_CLIENT_AUTH: "false"
      SOLR_SSL_WANT_CLIENT_AUTH: "false"
      SOLR_SSL_KEY_STORE_TYPE: "JKS"
      SOLR_SSL_TRUST_STORE_TYPE: "JKS"