version: '3.4'

services:
  solr840:
    image: solr:8.4.0
    volumes:
      - .:/opt/solr/server/solr
    ports:
      - 8983:8983
    working_dir: /opt/solr/server/solr
    user: root #image created with root user, so had to run it with root to be able to create and move files. But have to start solr with non-root user
    command: sh -c "runuser solr -c 'solr start -f'"
    environment:
      SOLR_SSL_ENABLED: "true"
      SOLR_SSL_KEY_STORE: "solr/solr-ssl.keystore.jks"
      SOLR_SSL_KEY_STORE_PASSWORD: "secret"
      SOLR_SSL_TRUST_STORE: "solr/solr-ssl.keystore.jks"
      SOLR_SSL_TRUST_STORE_PASSWORD: "secret"
      SOLR_SSL_NEED_CLIENT_AUTH: "false"
      SOLR_SSL_WANT_CLIENT_AUTH: "false"
      SOLR_SSL_KEY_STORE_TYPE: "JKS"
      SOLR_SSL_TRUST_STORE_TYPE: "JKS"